<?php
/**
 * Created by PhpStorm.
 * User: 65998
 * Date: 2018/4/27
 * Time: 16:03
 */

namespace app\admin\controller;


use app\model\Actors;

class Actor extends Init {
    function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $category = \app\model\Category::where('parent_id', 0)->select();

        $this->assign('category', $category);
    }

    public function index() {
        $cat_id = input('cat_id/d');
        $name   = input('name');

        $cat_id == true && $where[] = ['cat_id', '=', $cat_id];
        $name == true && $where[] = ['name', '=', "%$name%"];


        $list = Actors::where($where)->order('sort')->paginate();

        $this->assign('list', $list);
        $this->assign('cat_id',$cat_id);
        return $this->fetch();
    }

    //添加文章栏目
    function add() {
        $info['id'] = input('id');
        $this->assign('info', $info);
        if (isAjax()) {
            $this->save();
        }
        return $this->fetch('info');
    }

    //编辑文章栏目
    function edit() {
        $info = Actors::find(input('id'));

        $this->assign('info', $info);
        if (isAjax()) {
            $this->save();
        }
        return $this->fetch('info');
    }

    function save() {
        $data           = input('post.');
        $data['status'] = $data['status'] ? 1 : 0;

        if ($data['id']) {
            $res = Actors::update($data);
        } else {
            $data['insert_time'] = time();
            $res                 = Actors::insert($data);
        }

        $res ? $this->success('操作成功~') : $this->error('操作失败~');
    }
}