<?php
/**
 * Created by PhpStorm.
 * User: 65998
 * Date: 2018/5/20
 * Time: 7:08
 */

namespace app\home\controller;


use think\Controller;

class Base extends Controller {
    function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->view->filter(function($content){
            $tpl_replace_string = config('tpl_replace_string');
            if($tpl_replace_string){
                $arraySearch      = array_keys($tpl_replace_string);
                $content          = str_replace($arraySearch, $tpl_replace_string, $content);
            }

            //2014-11-28 修改 如果有HTTP 4xx 3xx 5xx 头部，禁止存储
            //2014-12-1 修改 对注入的网址 防止生成，例如 /game/lst/SortType/hot/-e8-90-8c-e5-85-94-e7-88-b1-e6-b6-88-e9-99-a4/.../index.shtml
            if (config('html_cache_on') && defined('HTML_FILE_NAME')) {
                //静态文件写入
                $this->initStorage()->write(HTML_FILE_NAME, $content);
            }
            return $content;
        });
    }


    // 初始化模板编译存储器
    private function initStorage() {
        $type  = config('html_cache_compile_type');
        $type  = $type ? $type : 'File';
        $class = false !== strpos($type, '\\') ? $type : '\\think\\template\\driver\\' . ucwords($type);
        return new $class();
    }
}